//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioShopFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid NidOrder { get; set; }
        public System.Guid NidUser { get; set; }
        public System.Guid NidProduct { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> NidShip { get; set; }
        public byte state { get; set; }
    
        public virtual Ship Ship { get; set; }
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
