//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioShopBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public System.Guid NidShip { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<byte> ShipVia { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> ZipCode { get; set; }
        public byte State { get; set; }
        public Nullable<decimal> ShipPrice { get; set; }
        public System.Guid NidOrder { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
